SELECT VALOR_TOTAL
FROM FACTURA 
WHERE FECHA_CREACION = '09/10/24';

SELECT SUM(VALOR_TOTAL) 
FROM FACTURA 
WHERE FECHA_CREACION = TO_DATE('09/10/24');

SELECT AVG(VALOR_TOTAL) 
FROM FACTURA 
WHERE FECHA_CREACION = '09/10/24';

--INNER JOIN O JOIN ES LA INTERSECCION

SELECT 
    TO_CHAR(FECHA_CREACION, 'YYYY') AS ANO,
    TO_CHAR(SUM(VALOR_TOTAL), '99G999G999') AS TOTAL_FACTURA
FROM 
    FACTURA
GROUP BY 
    TO_CHAR(FECHA_CREACION, 'YYYY')
ORDER BY 
    TOTAL_FACTURA DESC;

SELECT 
    TO_CHAR(FECHA_CREACION, 'YYYY-MM') AS MES,
    TO_CHAR(SUM(VALOR_TOTAL), '99G999G999') AS TOTAL_FACTURA
FROM 
    FACTURA
GROUP BY 
    TO_CHAR(FECHA_CREACION, 'YYYY-MM')
ORDER BY 
    TOTAL_FACTURA DESC
FETCH FIRST 1 ROWS ONLY;

-- CONSULTA EL VALOR TOTAL DE VENTAS EN AGOSTO
SELECT 
    SUM(f.VALOR_TOTAL) AS TOTAL_AGOSTO
FROM 
    FACTURA F
WHERE 
    TO_CHAR(F.FECHA_CREACION, 'MM') = '08'
    AND EXISTS (
        SELECT 1
        FROM DETALLE_FACTURA_CLIENTE DFC
        WHERE DFC.FACTURA_ID = F.ID);

-- CONSULTA EL VALOR TOTAL DE VENTAS POR AÑO Y LO ORGANIZA DE MAYOR A MENOR
SELECT 
    TO_CHAR(f.FECHA_CREACION, 'YYYY') AS ANO,
    TO_CHAR(SUM(f.VALOR_TOTAL), '99G999G999') AS TOTAL_ANO
FROM 
    FACTURA f
WHERE 
    EXISTS (
        SELECT 1
        FROM DETALLE_FACTURA_CLIENTE dfc
        WHERE dfc.FACTURA_ID = f.ID
    )
GROUP BY 
    TO_CHAR(f.FECHA_CREACION, 'YYYY')
ORDER BY 
    TOTAL_ANO DESC;

-- CONSULTA EL VALOR TOTAL DE VENTAS POR MES Y LO ORGANIZA DE MAYOR A MENOR, SUMA PARA EL MISMO MES SIN IMPORTAR EL AÑO
SELECT 
    TO_CHAR(f.FECHA_CREACION, 'MM') AS MES,
    TO_CHAR(SUM(f.VALOR_TOTAL), '99G999G999') AS TOTAL_MES
FROM 
    FACTURA f
WHERE 
    EXISTS (
        SELECT 1
        FROM DETALLE_FACTURA_CLIENTE dfc
        WHERE dfc.FACTURA_ID = f.ID
    )
GROUP BY 
    TO_CHAR(f.FECHA_CREACION, 'MM')
ORDER BY 
    TOTAL_MES DESC;

-- CONSULTA EL VALOR TOTAL DE VENTAS POR MES Y LO ORGANIZA DE MAYOR A MENOR PERO CON EL AÑO, ES DECIR, PARA CADA AÑO DA LAS VENTAS POR MES
SELECT 
    TO_CHAR(f.FECHA_CREACION, 'YYYY-MM') AS MES,
    TO_CHAR(SUM(f.VALOR_TOTAL), '99G999G999') AS TOTAL_MES
FROM 
    FACTURA f
WHERE 
    EXISTS (
        SELECT 1
        FROM DETALLE_FACTURA_CLIENTE dfc
        WHERE dfc.FACTURA_ID = f.ID
    )
GROUP BY 
    TO_CHAR(f.FECHA_CREACION, 'YYYY-MM')
ORDER BY 
    TOTAL_MES DESC;

-- CONSULTA EL VALOR TOTAL DE COMPRAS POR AÑO Y LO ORGANIZA DE MAYOR A MENOR
SELECT 
    TO_CHAR(f.FECHA_CREACION, 'YYYY') AS ANO,
    TO_CHAR(SUM(f.VALOR_TOTAL), '99G999G999') AS TOTAL_ANO
FROM 
    FACTURA f
WHERE 
    EXISTS (
        SELECT 1
        FROM DETALLE_FACTURA_INGREDIENTE DFI
        WHERE DFI.FACTURA_ID = f.ID
    )
GROUP BY 
    TO_CHAR(f.FECHA_CREACION, 'YYYY')
ORDER BY 
    TOTAL_ANO DESC;

-- CONSULTA EL VALOR TOTAL DE COMPRAS POR MES Y LO ORGANIZA DE MAYOR A MENOR, SUMA PARA EL MISMO MES SIN IMPORTAR EL AÑO
SELECT 
    TO_CHAR(f.FECHA_CREACION, 'MM') AS MES,
    TO_CHAR(SUM(f.VALOR_TOTAL), '99G999G999') AS TOTAL_MES
FROM 
    FACTURA f
WHERE 
    EXISTS (
        SELECT 1
        FROM DETALLE_FACTURA_INGREDIENTE DFI
        WHERE DFI.FACTURA_ID = f.ID
    )
GROUP BY 
    TO_CHAR(f.FECHA_CREACION, 'MM')
ORDER BY 
    TOTAL_MES DESC;

-- CONSULTA EL VALOR TOTAL DE COMPRAS POR MES Y LO ORGANIZA DE MAYOR A MENOR, SUMA EL MES POR AÑO
SELECT 
    TO_CHAR(f.FECHA_CREACION, 'YYYY-MM') AS MES,
    TO_CHAR(SUM(f.VALOR_TOTAL), '99G999G999') AS TOTAL_MES
FROM 
    FACTURA f
WHERE 
    EXISTS (
        SELECT 1
        FROM DETALLE_FACTURA_INGREDIENTE DFI
        WHERE DFI.FACTURA_ID = f.ID
    )
GROUP BY 
    TO_CHAR(f.FECHA_CREACION, 'YYYY-MM')
ORDER BY 
    TOTAL_MES DESC;